-- prepare tables
DROP TABLE IF EXISTS a;
DROP TABLE IF EXISTS b;
DROP TABLE IF EXISTS c;
DROP SEQUENCE IF EXISTS seq;

CREATE SEQUENCE seq START 1000000;
CREATE TABLE a
(
  word    VARCHAR NOT NULL ,
  id      INTEGER PRIMARY KEY DEFAULT nextval('seq')
);

CREATE TABLE b
(
  word    VARCHAR NOT NULL ,
  id2      INTEGER PRIMARY KEY DEFAULT nextval('seq')
);

CREATE TABLE c (  id INTEGER NOT NULL );